# Generated by Django 3.2.11 on 2022-06-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='DDuser',
            fields=[
                ('DDuserID', models.AutoField(db_column='DDuserID', primary_key=True, serialize=False)),
                ('userName', models.CharField(default=0, max_length=254)),
                ('dept', models.CharField(max_length=254, null=True)),
                ('DD', models.CharField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerOrders',
            fields=[
                ('orderID', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=254, null=True)),
                ('content', models.CharField(max_length=254, null=True)),
                ('hopeTime', models.CharField(max_length=254, null=True)),
                ('remarks', models.CharField(max_length=254, null=True)),
                ('projectID', models.IntegerField(default=0, null=True)),
                ('projectName', models.CharField(max_length=254, null=True)),
                ('agree', models.IntegerField(default=0, null=True)),
                ('repairerID', models.IntegerField(default=0, null=True)),
                ('repairerName', models.CharField(max_length=254, null=True)),
                ('seedTime', models.DateTimeField(max_length=254, null=True)),
                ('goTime', models.DateTimeField(max_length=254, null=True)),
                ('endTime', models.DateTimeField(max_length=254, null=True)),
                ('workingHours', models.IntegerField(default=0, null=True)),
                ('fault', models.CharField(max_length=254, null=True)),
                ('record', models.CharField(max_length=254, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=4, null=True)),
                ('confirm', models.CharField(max_length=254, null=True)),
                ('image', models.CharField(max_length=254, null=True)),
                ('lc', models.IntegerField(default=0, null=True)),
                ('state', models.CharField(max_length=254, null=True)),
                ('userID', models.IntegerField(default=0, null=True)),
                ('userName', models.CharField(max_length=254, null=True)),
                ('addTime', models.DateTimeField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerProject',
            fields=[
                ('projectID', models.AutoField(db_column='ProjectID', primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=254, null=True)),
                ('company', models.CharField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=254, null=True)),
                ('retentionMoney', models.DecimalField(decimal_places=4, default=0, max_digits=4, null=True)),
                ('startTime', models.DateTimeField(max_length=254, null=True)),
                ('endTime', models.DateTimeField(max_length=254, null=True)),
                ('state', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XCM',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userName', models.CharField(default=0, max_length=254)),
                ('img', models.CharField(default=0, max_length=254)),
                ('DD', models.CharField(max_length=254, null=True)),
                ('add_date', models.DateTimeField(max_length=254, null=True)),
            ],
        ),
    ]
