# Generated by Django 3.2.11 on 2022-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(db_column='companyId', primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('companyName', models.CharField(max_length=254, null=True)),
                ('code', models.CharField(max_length=254, null=True)),
                ('charge', models.CharField(max_length=254, null=True)),
                ('contacts', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=254, null=True)),
                ('start_date', models.CharField(max_length=254, null=True)),
                ('end_date', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('range', models.CharField(max_length=254, null=True)),
                ('capital', models.CharField(max_length=254, null=True)),
                ('is_luck', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(db_column='projectId', primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0, null=True)),
                ('projectName', models.CharField(max_length=254, null=True)),
                ('projectNo', models.CharField(max_length=254, null=True)),
                ('contacts', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=254, null=True)),
                ('add_date', models.CharField(max_length=254, null=True)),
                ('start_date', models.CharField(max_length=254, null=True)),
                ('end_date', models.CharField(max_length=254, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
