# Generated by Django 3.2.11 on 2022-03-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitID', models.AutoField(db_column='unitID', primary_key=True, serialize=False)),
                ('unitName', models.CharField(default=0, max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='projectId',
        ),
        migrations.AlterField(
            model_name='ordercompany',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Unit',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='itemName',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='Count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='Unit',
            field=models.CharField(default=0, max_length=254),
        ),
    ]
