# Generated by Django 3.2.11 on 2022-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
