# Generated by Django 3.2.11 on 2022-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('corporate_name', models.CharField(max_length=254)),
                ('corporate_code', models.CharField(max_length=254)),
                ('corporate_email', models.CharField(max_length=254)),
                ('corporate_charge', models.CharField(max_length=254)),
                ('corporate_contacts', models.CharField(max_length=254)),
                ('corporate_phone', models.CharField(max_length=254)),
                ('corporate_tel', models.CharField(max_length=254)),
                ('corporate_start_date', models.CharField(max_length=254)),
                ('corporate_end_date', models.CharField(max_length=254)),
                ('corporate_address', models.CharField(max_length=254)),
                ('corporate_range', models.CharField(max_length=254)),
                ('corporate_capital', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
